stages:
  - deploy

deploy_to_raspberry_pi:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client rsync
  script:
    - rsync -avz --delete ./automation $PI_USER@$PI_HOST:/vestia
  only:
    - main  
