name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.PI_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy to Raspberry Pi
      env:
        PI_USER: ${{ secrets.PI_USER }}
        PI_HOST: ${{ secrets.PI_HOST }}
        PI_PATH: ${{ secrets.PI_PATH }}
      run: |
        rsync -avz --delete ./automation $PI_USER@$PI_HOST:$PI_PATH
