name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main  # or the branch you want to trigger the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key for authentication
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.PI_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        # Ensure the Raspberry Pi's SSH key is added to known_hosts
        ssh-keyscan -H ${{ secrets.PI_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to Raspberry Pi
      env:
        PI_USER: ${{ secrets.PI_USER }}
        PI_HOST: ${{ secrets.PI_HOST }}
        PI_PATH: ${{ secrets.PI_PATH }}
      run: |
        # Use rsync to copy files to the Pi
        rsync -avz --delete ./automation $PI_USER@$PI_HOST:$PI_PATH
