name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main  # or the branch you want to trigger the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List files in the repository
      run: |
        ls -alh

    # Step 2: Set up SSH key for authentication
    - name: Set up SSH key for authentication
      run: |
        # Create the .ssh directory if it doesn't exist
        mkdir -p ~/.ssh
        
        # Write the private key stored in GitHub Secrets to the id_rsa file
        echo "${{ secrets.PI_SSH_KEY }}" > ~/.ssh/id_rsa
        
        # Set correct permissions for the private key
        chmod 600 ~/.ssh/id_rsa
        
        # Add the Raspberry Pi to the known hosts file to avoid SSH verification prompts
        ssh-keyscan -H ${{ secrets.PI_HOST }} >> ~/.ssh/known_hosts
        
        # Start the SSH agent
        eval $(ssh-agent -s)
        
        # Add the private key to the SSH agent
        ssh-add ~/.ssh/id_rsa

    # Step 3: Ensure the target directory exists on Raspberry Pi
    - name: Ensure target directory exists on Raspberry Pi
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.PI_USER }}@${{ secrets.PI_HOST }} "mkdir -p /home/${{ secrets.PI_USER }}"

    # Step 4: Deploy crontab file to Raspberry Pi
    - name: Deploy crontab.txt to Raspberry Pi
      run: |
        # Use rsync to copy crontab.txt from the Scheduling folder
        rsync -avz --delete -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" ./Scheduling/crontab.txt ${{ secrets.PI_USER }}@${{ secrets.PI_HOST }}:/home/${{ secrets.PI_USER }}/crontab.txt
        
        # SSH into the Raspberry Pi to install the crontab file
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.PI_USER }}@${{ secrets.PI_HOST }} << EOF
            # Install the new crontab
            crontab /home/${{ secrets.PI_USER }}/crontab.txt
            
            # Confirm that the crontab was updated
            echo "Crontab updated successfully."
        EOF
